### ISSUE TITLE
What do it do

### ISSUE THREAD

**Issue by ChibiBlaziken** [Kylemc1413/QuestMods#1]
https://sidequestvr.com/#/app/94

Apologies but new users just starting on Quest have no earthly idea what this application/ mod even is over in Sidequest and
"This adds a host of new things you can do with your maps as a mapper, and allows you to play said maps as a player."

that is the same as saying

"download this and it does things and stuff with maps"

if you could update it to give a better description really quick that would be wonderful, thank you greatly for contributing to the growth and expansion of VR and it's capabilities

**Comment by Kylemc1413** [comment]
Since it’s a port of a pc mod with a proper readme, it didn’t occur to me to clarify that on the sidequest page, I’ll look at updating that when I’m free
