### ISSUE TITLE
Needs a new update for 1.6.3. Whenever starting a map all of the walls and blocks are ten miles from your platform.

### ISSUE THREAD

**Issue by ThePlazmaPizza** [Kylemc1413/QuestMods#15]

**Comment by DamienRCA** [comment]
YES PLEASE FIX ASAP.. sorry to sound pushy and all
EDIT: this happens with all maps

**Comment by roguetr** [comment]
Can confirm, just updated to 1.6.3 and blocks now appear of to the left and are no longer centred.

**Comment by cynsupercat** [comment]
There's a PR up for this https://github.com/Kylemc1413/QuestMods/pull/16 

Hopefully it'll get merged soon.

**Comment by roguetr** [comment]
The nonofficial updated version has been posted on discord.

**Comment by Terifictaylor10** [comment]
where can I find the discord?

**Comment by roguetr** [comment]
https://discord.gg/beatsabermods

**Comment by FlorianObermayer** [comment]
> There's a PR up for this #16
> 
> Hopefully it'll get merged soon.

Can confirm this also works with Beat Saber update `1.7.0`

**Comment by roguetr** [comment]
Can also confirm working with 1.7.0 but the newly added official songs
won't be available after installing the current version of BMBF.
