### ISSUE TITLE
Mapping Extension Doesn’t work on 1.4.3

### ISSUE THREAD

**Issue by AsoDesu** [Kylemc1413/QuestMods#7]
The mapping extension mod doesn’t work on 1.4.3, it will enable but when you launch Beat Saber it crashes.

**Comment by jhu104** [comment]
There is a prebuilt version of the zip that at found here https://bsaber.com/oculus-quest-custom-songs/
that supports 1.4.3
https://cdn.discordapp.com/attachments/599740772547428361/632343679440519178/MappingExtensions_0.14.0.zip
